<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * 0 to suspend or 1 to activate
 */
class ActivateEnum
{
    /**
     * TODO: Write general description for this element
     */
    const ENUM_1 = 1;

    /**
     * TODO: Write general description for this element
     */
    const ENUM_0 = 0;
}
