<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * The URL for the audio file that is to be played during the conference. Multiple audio files can be
 * chained by using a semicolon.
 */
class AudioUrlEnum
{
    /**
     * TODO: Write general description for this element
     */
    const MP3 = "mp3";

    /**
     * TODO: Write general description for this element
     */
    const WAV = "wav";
}
