<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body11 implements JsonSerializable
{
    /**
     * URL pointing to the location of the audio file that is to be transcribed.
     * @required
     * @var string $audiourl public property
     */
    public $audiourl;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $audiourl Initialization value for $this->audiourl
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->audiourl = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['audiourl'] = $this->audiourl;

        return $json;
    }
}
