<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body70 implements JsonSerializable
{
    /**
     * Which page of the overall response will be returned. Page indexing starts at 1.
     * @maps Page
     * @var integer|null $page public property
     */
    public $page;

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     * @maps PageSize
     * @var integer|null $pageSize public property
     */
    public $pageSize;

    /**
     * The capability supported by the number.Number type either SMS,Voice or all
     * @maps NumberType
     * @var string|null $numberType public property
     */
    public $numberType;

    /**
     * A human-readable label added to the number object.
     * @maps FriendlyName
     * @var string|null $friendlyName public property
     */
    public $friendlyName;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $page         Initialization value for $this->page
     * @param integer $pageSize     Initialization value for $this->pageSize
     * @param string  $numberType   Initialization value for $this->numberType
     * @param string  $friendlyName Initialization value for $this->friendlyName
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->page         = func_get_arg(0);
            $this->pageSize     = func_get_arg(1);
            $this->numberType   = func_get_arg(2);
            $this->friendlyName = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Page']         = $this->page;
        $json['PageSize']     = $this->pageSize;
        $json['NumberType']   = $this->numberType;
        $json['FriendlyName'] = $this->friendlyName;

        return $json;
    }
}
