<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body34 implements JsonSerializable
{
    /**
     * The SubaccountSid to be deleted
     * @required
     * @maps SubAccountSID
     * @var string $subAccountSID public property
     */
    public $subAccountSID;

    /**
     * 0 to delete or 1 to merge numbers to parent account.
     * @required
     * @maps MergeNumber
     * @var int $mergeNumber public property
     */
    public $mergeNumber;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $subAccountSID Initialization value for $this->subAccountSID
     * @param int    $mergeNumber   Initialization value for $this->mergeNumber
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->subAccountSID = func_get_arg(0);
            $this->mergeNumber   = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['SubAccountSID'] = $this->subAccountSID;
        $json['MergeNumber']   = $this->mergeNumber;

        return $json;
    }
}
