<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body14 implements JsonSerializable
{
    /**
     * A valid 10-digit Ytel number (E.164 format).
     * @required
     * @maps PhoneNumber
     * @var string $phoneNumber public property
     */
    public $phoneNumber;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $phoneNumber Initialization value for $this->phoneNumber
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->phoneNumber = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['PhoneNumber'] = $this->phoneNumber;

        return $json;
    }
}
