<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body38 implements JsonSerializable
{
    /**
     * Only list messages sent from this Short Code
     * @maps Shortcode
     * @var string|null $shortcode public property
     */
    public $shortcode;

    /**
     * Only list messages sent to this number
     * @maps To
     * @var string|null $to public property
     */
    public $to;

    /**
     * Only list messages sent with the specified date
     * @maps DateSent
     * @var string|null $dateSent public property
     */
    public $dateSent;

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     * @maps Page
     * @var integer|null $page public property
     */
    public $page;

    /**
     * The count of objects to return per page.
     * @maps PageSize
     * @var integer|null $pageSize public property
     */
    public $pageSize;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $shortcode Initialization value for $this->shortcode
     * @param string  $to        Initialization value for $this->to
     * @param string  $dateSent  Initialization value for $this->dateSent
     * @param integer $page      Initialization value for $this->page
     * @param integer $pageSize  Initialization value for $this->pageSize
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->shortcode = func_get_arg(0);
            $this->to        = func_get_arg(1);
            $this->dateSent  = func_get_arg(2);
            $this->page      = func_get_arg(3);
            $this->pageSize  = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Shortcode'] = $this->shortcode;
        $json['To']        = $this->to;
        $json['DateSent']  = $this->dateSent;
        $json['Page']      = $this->page;
        $json['PageSize']  = $this->pageSize;

        return $json;
    }
}
