<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body50 implements JsonSerializable
{
    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     * @var integer|null $page public property
     */
    public $page;

    /**
     * The count of objects to return per page.
     * @var integer|null $pagesize public property
     */
    public $pagesize;

    /**
     * The state of the transcription.
     * @var string|null $status public property
     */
    public $status;

    /**
     * The date the transcription took place.
     * @var string|null $dateTranscribed public property
     */
    public $dateTranscribed;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $page            Initialization value for $this->page
     * @param integer $pagesize        Initialization value for $this->pagesize
     * @param string  $status          Initialization value for $this->status
     * @param string  $dateTranscribed Initialization value for $this->dateTranscribed
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->page            = func_get_arg(0);
            $this->pagesize        = func_get_arg(1);
            $this->status          = func_get_arg(2);
            $this->dateTranscribed = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['page']            = $this->page;
        $json['pagesize']        = $this->pagesize;
        $json['status']          = $this->status;
        $json['dateTranscribed'] = $this->dateTranscribed;

        return $json;
    }
}
