<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body21 implements JsonSerializable
{
    /**
     * A valid address that will receive the email. Multiple addresses can be separated by using commas.
     * @required
     * @maps To
     * @var string $to public property
     */
    public $to;

    /**
     * Specifies the type of email to be sent
     * @required
     * @maps Type
     * @var string $type public property
     */
    public $type;

    /**
     * The subject of the mail. Must be a valid string.
     * @required
     * @maps Subject
     * @var string $subject public property
     */
    public $subject;

    /**
     * The email message that is to be sent in the text.
     * @required
     * @maps Message
     * @var string $message public property
     */
    public $message;

    /**
     * A valid address that will send the email.
     * @maps From
     * @var string|null $from public property
     */
    public $from;

    /**
     * Carbon copy. A valid address that will receive the email. Multiple addresses can be separated by
     * using commas.
     * @maps Cc
     * @var string|null $cc public property
     */
    public $cc;

    /**
     * Blind carbon copy. A valid address that will receive the email. Multiple addresses can be separated
     * by using commas.
     * @maps Bcc
     * @var string|null $bcc public property
     */
    public $bcc;

    /**
     * A file that is attached to the email. Must be less than 7 MB in size.
     * @maps Attachment
     * @var string|null $attachment public property
     */
    public $attachment;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $to         Initialization value for $this->to
     * @param string $type       Initialization value for $this->type
     * @param string $subject    Initialization value for $this->subject
     * @param string $message    Initialization value for $this->message
     * @param string $from       Initialization value for $this->from
     * @param string $cc         Initialization value for $this->cc
     * @param string $bcc        Initialization value for $this->bcc
     * @param string $attachment Initialization value for $this->attachment
     */
    public function __construct()
    {
        if (8 == func_num_args()) {
            $this->to         = func_get_arg(0);
            $this->type       = func_get_arg(1);
            $this->subject    = func_get_arg(2);
            $this->message    = func_get_arg(3);
            $this->from       = func_get_arg(4);
            $this->cc         = func_get_arg(5);
            $this->bcc        = func_get_arg(6);
            $this->attachment = func_get_arg(7);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['To']         = $this->to;
        $json['Type']       = $this->type;
        $json['Subject']    = $this->subject;
        $json['Message']    = $this->message;
        $json['From']       = $this->from;
        $json['Cc']         = $this->cc;
        $json['Bcc']        = $this->bcc;
        $json['Attachment'] = $this->attachment;

        return $json;
    }
}
