<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body30 implements JsonSerializable
{
    /**
     * The email address to be remove from the bounced email list.
     * @required
     * @maps Email
     * @var string $email public property
     */
    public $email;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $email Initialization value for $this->email
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->email = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Email'] = $this->email;

        return $json;
    }
}
