<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body66 implements JsonSerializable
{
    /**
     * A valid 10-digit Ytel number (E.164 format).
     * @required
     * @var string $phonenumber public property
     */
    public $phonenumber;

    /**
     * A specific Accountsid from where Number is getting transfer.
     * @required
     * @var string $fromaccountsid public property
     */
    public $fromaccountsid;

    /**
     * A specific Accountsid to which Number is getting transfer.
     * @required
     * @var string $toaccountsid public property
     */
    public $toaccountsid;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $phonenumber    Initialization value for $this->phonenumber
     * @param string $fromaccountsid Initialization value for $this->fromaccountsid
     * @param string $toaccountsid   Initialization value for $this->toaccountsid
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->phonenumber    = func_get_arg(0);
            $this->fromaccountsid = func_get_arg(1);
            $this->toaccountsid   = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['phonenumber']    = $this->phonenumber;
        $json['fromaccountsid'] = $this->fromaccountsid;
        $json['toaccountsid']   = $this->toaccountsid;

        return $json;
    }
}
