<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body62 implements JsonSerializable
{
    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     * @var integer|null $page public property
     */
    public $page;

    /**
     * Number of individual resources listed in the response per page
     * @var integer|null $pagesize public property
     */
    public $pagesize;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $page     Initialization value for $this->page
     * @param integer $pagesize Initialization value for $this->pagesize
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->page     = func_get_arg(0);
            $this->pagesize = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['page']     = $this->page;
        $json['pagesize'] = $this->pagesize;

        return $json;
    }
}
