<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body27 implements JsonSerializable
{
    /**
     * The unique identifier of each call resource
     * @required
     * @maps CallSid
     * @var string $callSid public property
     */
    public $callSid;

    /**
     * DTMF digits to play to the call. 0-9, #, *, W, or w
     * @required
     * @maps PlayDtmf
     * @var string $playDtmf public property
     */
    public $playDtmf;

    /**
     * The leg of the call DTMF digits should be sent to
     * @maps PlayDtmfDirection
     * @var string|null $playDtmfDirection public property
     */
    public $playDtmfDirection;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $callSid           Initialization value for $this->callSid
     * @param string $playDtmf          Initialization value for $this->playDtmf
     * @param string $playDtmfDirection Initialization value for $this->playDtmfDirection
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->callSid           = func_get_arg(0);
            $this->playDtmf          = func_get_arg(1);
            $this->playDtmfDirection = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['CallSid']           = $this->callSid;
        $json['PlayDtmf']          = $this->playDtmf;
        $json['PlayDtmfDirection'] = $this->playDtmfDirection;

        return $json;
    }
}
