<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body36 implements JsonSerializable
{
    /**
     * Filter account information based on date.
     * @required
     * @maps Date
     * @var string $date public property
     */
    public $date;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $date Initialization value for $this->date
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->date = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Date'] = $this->date;

        return $json;
    }
}
