<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body72 implements JsonSerializable
{
    /**
     * Specifies the multiple phone numbers for check updated spamscore .
     * @required
     * @maps Phonenumber
     * @var string $phonenumber public property
     */
    public $phonenumber;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $phonenumber Initialization value for $this->phonenumber
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->phonenumber = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Phonenumber'] = $this->phonenumber;

        return $json;
    }
}
