<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body73 implements JsonSerializable
{
    /**
     * The capability the number supports.
     * @required
     * @maps NumberType
     * @var string $numberType public property
     */
    public $numberType;

    /**
     * Specifies the area code for the returned list of available numbers. Only available for North
     * American numbers.
     * @required
     * @maps AreaCode
     * @var string $areaCode public property
     */
    public $areaCode;

    /**
     * A positive integer that tells how many number you want to buy at a time.
     * @required
     * @maps Quantity
     * @var string $quantity public property
     */
    public $quantity;

    /**
     * If desired quantity is unavailable purchase what is available .
     * @maps Leftover
     * @var string|null $leftover public property
     */
    public $leftover;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $numberType Initialization value for $this->numberType
     * @param string $areaCode   Initialization value for $this->areaCode
     * @param string $quantity   Initialization value for $this->quantity
     * @param string $leftover   Initialization value for $this->leftover
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->numberType = func_get_arg(0);
            $this->areaCode   = func_get_arg(1);
            $this->quantity   = func_get_arg(2);
            $this->leftover   = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['NumberType'] = $this->numberType;
        $json['AreaCode']   = $this->areaCode;
        $json['Quantity']   = $this->quantity;
        $json['Leftover']   = $this->leftover;

        return $json;
    }
}
