<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body74 implements JsonSerializable
{
    /**
     * The unique identifier for the voice call.
     * @required
     * @var string $callSid public property
     */
    public $callSid;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $callSid Initialization value for $this->callSid
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->callSid = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['callSid'] = $this->callSid;

        return $json;
    }
}
