<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body76 implements JsonSerializable
{
    /**
     * Only list Short Code Assignment sent from this Short Code
     * @maps Shortcode
     * @var string|null $shortcode public property
     */
    public $shortcode;

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     * @var string|null $page public property
     */
    public $page;

    /**
     * The count of objects to return per page.
     * @var string|null $pagesize public property
     */
    public $pagesize;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $shortcode Initialization value for $this->shortcode
     * @param string $page      Initialization value for $this->page
     * @param string $pagesize  Initialization value for $this->pagesize
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->shortcode = func_get_arg(0);
            $this->page      = func_get_arg(1);
            $this->pagesize  = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Shortcode'] = $this->shortcode;
        $json['page']      = $this->page;
        $json['pagesize']  = $this->pagesize;

        return $json;
    }
}
