<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body22 implements JsonSerializable
{
    /**
     * The unique identifier of each call resource
     * @required
     * @maps CallSid
     * @var string $callSid public property
     */
    public $callSid;

    /**
     * URL to sound that should be played. You also can add more than one audio file using semicolons e.g.
     * http://example.com/audio1.mp3;http://example.com/audio2.wav
     * @required
     * @maps AudioUrl
     * @var string $audioUrl public property
     */
    public $audioUrl;

    /**
     * Valid alphanumeric string that should be played to the In-progress call.
     * @required
     * @maps SayText
     * @var string $sayText public property
     */
    public $sayText;

    /**
     * Time limit in seconds for audio play back
     * @maps Length
     * @var integer|null $length public property
     */
    public $length;

    /**
     * The leg of the call audio will be played to
     * @maps Direction
     * @var string|null $direction public property
     */
    public $direction;

    /**
     * If false, all other audio will be muted
     * @maps Mix
     * @var bool|null $mix public property
     */
    public $mix;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $callSid   Initialization value for $this->callSid
     * @param string  $audioUrl  Initialization value for $this->audioUrl
     * @param string  $sayText   Initialization value for $this->sayText
     * @param integer $length    Initialization value for $this->length
     * @param string  $direction Initialization value for $this->direction
     * @param bool    $mix       Initialization value for $this->mix
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->callSid   = func_get_arg(0);
            $this->audioUrl  = func_get_arg(1);
            $this->sayText   = func_get_arg(2);
            $this->length    = func_get_arg(3);
            $this->direction = func_get_arg(4);
            $this->mix       = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['CallSid']   = $this->callSid;
        $json['AudioUrl']  = $this->audioUrl;
        $json['SayText']   = $this->sayText;
        $json['Length']    = $this->length;
        $json['Direction'] = $this->direction;
        $json['Mix']       = $this->mix;

        return $json;
    }
}
