<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body33 implements JsonSerializable
{
    /**
     * The starting point of the list of blocked emails that should be returned.
     * @maps Offset
     * @var string|null $offset public property
     */
    public $offset;

    /**
     * The count of results that should be returned.
     * @maps Limit
     * @var string|null $limit public property
     */
    public $limit;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $offset Initialization value for $this->offset
     * @param string $limit  Initialization value for $this->limit
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->offset = func_get_arg(0);
            $this->limit  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Offset'] = $this->offset;
        $json['Limit']  = $this->limit;

        return $json;
    }
}
