<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body24 implements JsonSerializable
{
    /**
     * The unique identifier for the in-progress voice call.
     * @required
     * @maps CallSid
     * @var string $callSid public property
     */
    public $callSid;

    /**
     * The direction the audio effect should be placed on. If IN, the effects will occur on the incoming
     * audio stream. If OUT, the effects will occur on the outgoing audio stream.
     * @maps AudioDirection
     * @var string|null $audioDirection public property
     */
    public $audioDirection;

    /**
     * Set the pitch in semitone (half-step) intervals. Value between -14 and 14
     * @maps PitchSemiTones
     * @var double|null $pitchSemiTones public property
     */
    public $pitchSemiTones;

    /**
     * Set the pitch in octave intervals.. Value between -1 and 1
     * @maps PitchOctaves
     * @var double|null $pitchOctaves public property
     */
    public $pitchOctaves;

    /**
     * Set the pitch (lowness/highness) of the audio. The higher the value, the higher the pitch. Value
     * greater than 0
     * @maps Pitch
     * @var double|null $pitch public property
     */
    public $pitch;

    /**
     * Set the rate for audio. The lower the value, the lower the rate. value greater than 0
     * @maps Rate
     * @var double|null $rate public property
     */
    public $rate;

    /**
     * Set the tempo (speed) of the audio. A higher value denotes a faster tempo. Value greater than 0
     * @maps Tempo
     * @var double|null $tempo public property
     */
    public $tempo;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $callSid        Initialization value for $this->callSid
     * @param string $audioDirection Initialization value for $this->audioDirection
     * @param double $pitchSemiTones Initialization value for $this->pitchSemiTones
     * @param double $pitchOctaves   Initialization value for $this->pitchOctaves
     * @param double $pitch          Initialization value for $this->pitch
     * @param double $rate           Initialization value for $this->rate
     * @param double $tempo          Initialization value for $this->tempo
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->callSid        = func_get_arg(0);
            $this->audioDirection = func_get_arg(1);
            $this->pitchSemiTones = func_get_arg(2);
            $this->pitchOctaves   = func_get_arg(3);
            $this->pitch          = func_get_arg(4);
            $this->rate           = func_get_arg(5);
            $this->tempo          = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['CallSid']        = $this->callSid;
        $json['AudioDirection'] = $this->audioDirection;
        $json['PitchSemiTones'] = $this->pitchSemiTones;
        $json['PitchOctaves']   = $this->pitchOctaves;
        $json['Pitch']          = $this->pitch;
        $json['Rate']           = $this->rate;
        $json['Tempo']          = $this->tempo;

        return $json;
    }
}
