<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body48 implements JsonSerializable
{
    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     * @var integer|null $page public property
     */
    public $page;

    /**
     * The count of objects to return per page.
     * @var integer|null $pagesize public property
     */
    public $pagesize;

    /**
     * Filter results by creation date
     * @maps Datecreated
     * @var string|null $datecreated public property
     */
    public $datecreated;

    /**
     * The unique identifier for a call.
     * @var string|null $callsid public property
     */
    public $callsid;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $page        Initialization value for $this->page
     * @param integer $pagesize    Initialization value for $this->pagesize
     * @param string  $datecreated Initialization value for $this->datecreated
     * @param string  $callsid     Initialization value for $this->callsid
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->page        = func_get_arg(0);
            $this->pagesize    = func_get_arg(1);
            $this->datecreated = func_get_arg(2);
            $this->callsid     = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['page']        = $this->page;
        $json['pagesize']    = $this->pagesize;
        $json['Datecreated'] = $this->datecreated;
        $json['callsid']     = $this->callsid;

        return $json;
    }
}
