<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body13 implements JsonSerializable
{
    /**
     * The unique identifier for a recording.
     * @required
     * @var string $recordingsid public property
     */
    public $recordingsid;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $recordingsid Initialization value for $this->recordingsid
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->recordingsid = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['recordingsid'] = $this->recordingsid;

        return $json;
    }
}
