<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body7 implements JsonSerializable
{
    /**
     * The unique identifier for a conference object.
     * @required
     * @maps ConferenceSid
     * @var string $conferenceSid public property
     */
    public $conferenceSid;

    /**
     * The unique identifier for a participant object.
     * @required
     * @maps ParticipantSid
     * @var string $participantSid public property
     */
    public $participantSid;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $conferenceSid  Initialization value for $this->conferenceSid
     * @param string $participantSid Initialization value for $this->participantSid
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->conferenceSid  = func_get_arg(0);
            $this->participantSid = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['ConferenceSid']  = $this->conferenceSid;
        $json['ParticipantSid'] = $this->participantSid;

        return $json;
    }
}
