<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body1 implements JsonSerializable
{
    /**
     * The 10-digit SMS-enabled Ytel number (E.164 format) in which the message is sent.
     * @required
     * @maps From
     * @var string $from public property
     */
    public $from;

    /**
     * The 10-digit phone number (E.164 format) that will receive the message.
     * @required
     * @maps To
     * @var string $to public property
     */
    public $to;

    /**
     * The body message that is to be sent in the text.
     * @required
     * @maps Body
     * @var string $body public property
     */
    public $body;

    /**
     * Specifies the HTTP method used to request the required URL once SMS sent.
     * @maps Method
     * @var string|null $method public property
     */
    public $method;

    /**
     * URL that can be requested to receive notification when SMS has Sent. A set of default parameters
     * will be sent here once the SMS is finished.
     * @maps MessageStatusCallback
     * @var string|null $messageStatusCallback public property
     */
    public $messageStatusCallback;

    /**
     * Check's 'to' number can receive sms or not using Carrier API, if wireless = true then text sms is
     * sent, else wireless = false then call is recieved to end user with audible message.
     * @maps Smartsms
     * @var bool|null $smartsms public property
     */
    public $smartsms;

    /**
     * Delivery reports are a method to tell your system if the message has arrived on the destination
     * phone.
     * @maps DeliveryStatus
     * @var bool|null $deliveryStatus public property
     */
    public $deliveryStatus;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $from                  Initialization value for $this->from
     * @param string $to                    Initialization value for $this->to
     * @param string $body                  Initialization value for $this->body
     * @param string $method                Initialization value for $this->method
     * @param string $messageStatusCallback Initialization value for $this->messageStatusCallback
     * @param bool   $smartsms              Initialization value for $this->smartsms
     * @param bool   $deliveryStatus        Initialization value for $this->deliveryStatus
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->from                  = func_get_arg(0);
            $this->to                    = func_get_arg(1);
            $this->body                  = func_get_arg(2);
            $this->method                = func_get_arg(3);
            $this->messageStatusCallback = func_get_arg(4);
            $this->smartsms              = func_get_arg(5);
            $this->deliveryStatus        = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['From']                  = $this->from;
        $json['To']                    = $this->to;
        $json['Body']                  = $this->body;
        $json['Method']                = $this->method;
        $json['MessageStatusCallback'] = $this->messageStatusCallback;
        $json['Smartsms']              = $this->smartsms;
        $json['DeliveryStatus']        = $this->deliveryStatus;

        return $json;
    }
}
