<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body23 implements JsonSerializable
{
    /**
     * The unique identifier of each call resource
     * @required
     * @maps CallSid
     * @var string $callSid public property
     */
    public $callSid;

    /**
     * Set true to initiate recording or false to terminate recording
     * @required
     * @maps Record
     * @var bool $record public property
     */
    public $record;

    /**
     * The leg of the call to record
     * @maps Direction
     * @var string|null $direction public property
     */
    public $direction;

    /**
     * Time in seconds the recording duration should not exceed
     * @maps TimeLimit
     * @var integer|null $timeLimit public property
     */
    public $timeLimit;

    /**
     * URL consulted after the recording completes
     * @maps CallBackUrl
     * @var string|null $callBackUrl public property
     */
    public $callBackUrl;

    /**
     * Format of the recording file. Can be .mp3 or .wav
     * @maps Fileformat
     * @var string|null $fileformat public property
     */
    public $fileformat;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $callSid     Initialization value for $this->callSid
     * @param bool    $record      Initialization value for $this->record
     * @param string  $direction   Initialization value for $this->direction
     * @param integer $timeLimit   Initialization value for $this->timeLimit
     * @param string  $callBackUrl Initialization value for $this->callBackUrl
     * @param string  $fileformat  Initialization value for $this->fileformat
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->callSid     = func_get_arg(0);
            $this->record      = func_get_arg(1);
            $this->direction   = func_get_arg(2);
            $this->timeLimit   = func_get_arg(3);
            $this->callBackUrl = func_get_arg(4);
            $this->fileformat  = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['CallSid']     = $this->callSid;
        $json['Record']      = $this->record;
        $json['Direction']   = $this->direction;
        $json['TimeLimit']   = $this->timeLimit;
        $json['CallBackUrl'] = $this->callBackUrl;
        $json['Fileformat']  = $this->fileformat;

        return $json;
    }
}
