<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body40 implements JsonSerializable
{
    /**
     * The Short Code number that is the sender of this message
     * @required
     * @var string $shortcode public property
     */
    public $shortcode;

    /**
     * A valid 10-digit number that should receive the message
     * @required
     * @var string $to public property
     */
    public $to;

    /**
     * The unique identifier for the template used for the message
     * @required
     * @var string $templateid public property
     */
    public $templateid;

    /**
     * format of your data, example: {companyname}:test,{otpcode}:1234
     * @required
     * @var string $data public property
     */
    public $data;

    /**
     * Specifies the HTTP method used to request the required URL once the Short Code message is sent.
     * @maps Method
     * @var string|null $method public property
     */
    public $method;

    /**
     * URL that can be requested to receive notification when Short Code message was sent.
     * @maps MessageStatusCallback
     * @var string|null $messageStatusCallback public property
     */
    public $messageStatusCallback;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $shortcode             Initialization value for $this->shortcode
     * @param string $to                    Initialization value for $this->to
     * @param string $templateid            Initialization value for $this->templateid
     * @param string $data                  Initialization value for $this->data
     * @param string $method                Initialization value for $this->method
     * @param string $messageStatusCallback Initialization value for $this->messageStatusCallback
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->shortcode             = func_get_arg(0);
            $this->to                    = func_get_arg(1);
            $this->templateid            = func_get_arg(2);
            $this->data                  = func_get_arg(3);
            $this->method                = func_get_arg(4);
            $this->messageStatusCallback = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['shortcode']             = $this->shortcode;
        $json['to']                    = $this->to;
        $json['templateid']            = $this->templateid;
        $json['data']                  = $this->data;
        $json['Method']                = $this->method;
        $json['MessageStatusCallback'] = $this->messageStatusCallback;

        return $json;
    }
}
