<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body52 implements JsonSerializable
{
    /**
     * Your dedicated shortcode
     * @required
     * @var integer $shortcode public property
     */
    public $shortcode;

    /**
     * The number to send your SMS to
     * @required
     * @var double $to public property
     */
    public $to;

    /**
     * The body of your message
     * @required
     * @var string $body public property
     */
    public $body;

    /**
     * Specifies the HTTP method used to request the required URL once the Short Code message is sent.GET
     * or POST
     * @var string|null $method public property
     */
    public $method;

    /**
     * URL that can be requested to receive notification when Short Code message was sent.
     * @var string|null $messagestatuscallback public property
     */
    public $messagestatuscallback;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $shortcode             Initialization value for $this->shortcode
     * @param double  $to                    Initialization value for $this->to
     * @param string  $body                  Initialization value for $this->body
     * @param string  $method                Initialization value for $this->method
     * @param string  $messagestatuscallback Initialization value for $this->messagestatuscallback
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->shortcode             = func_get_arg(0);
            $this->to                    = func_get_arg(1);
            $this->body                  = func_get_arg(2);
            $this->method                = func_get_arg(3);
            $this->messagestatuscallback = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['shortcode']             = $this->shortcode;
        $json['to']                    = $this->to;
        $json['body']                  = $this->body;
        $json['method']                = $this->method;
        $json['messagestatuscallback'] = $this->messagestatuscallback;

        return $json;
    }
}
