<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body43 implements JsonSerializable
{
    /**
     * A valid Ytel Voice enabled number (E.164 format) that will be initiating the phone call.
     * @required
     * @maps From
     * @var string $from public property
     */
    public $from;

    /**
     * A required secondary Caller ID for RVM to work.
     * @required
     * @maps RVMCallerId
     * @var string $rVMCallerId public property
     */
    public $rVMCallerId;

    /**
     * A valid number (E.164 format) that will receive the phone call.
     * @required
     * @maps To
     * @var string $to public property
     */
    public $to;

    /**
     * The URL requested once the RVM connects. A set of default parameters will be sent here.
     * @required
     * @maps VoiceMailURL
     * @var string $voiceMailURL public property
     */
    public $voiceMailURL;

    /**
     * Specifies the HTTP method used to request the required URL once call connects.
     * @maps Method
     * @var string|null $method public property
     */
    public $method;

    /**
     * URL that can be requested to receive notification when call has ended. A set of default parameters
     * will be sent here once the call is finished.
     * @maps StatusCallBackUrl
     * @var string|null $statusCallBackUrl public property
     */
    public $statusCallBackUrl;

    /**
     * Specifies the HTTP method used to request the required StatusCallBackUrl once call connects.
     * @maps StatsCallBackMethod
     * @var string|null $statsCallBackMethod public property
     */
    public $statsCallBackMethod;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $from                Initialization value for $this->from
     * @param string $rVMCallerId         Initialization value for $this->rVMCallerId
     * @param string $to                  Initialization value for $this->to
     * @param string $voiceMailURL        Initialization value for $this->voiceMailURL
     * @param string $method              Initialization value for $this->method
     * @param string $statusCallBackUrl   Initialization value for $this->statusCallBackUrl
     * @param string $statsCallBackMethod Initialization value for $this->statsCallBackMethod
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->from                = func_get_arg(0);
            $this->rVMCallerId         = func_get_arg(1);
            $this->to                  = func_get_arg(2);
            $this->voiceMailURL        = func_get_arg(3);
            $this->method              = func_get_arg(4);
            $this->statusCallBackUrl   = func_get_arg(5);
            $this->statsCallBackMethod = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['From']                = $this->from;
        $json['RVMCallerId']         = $this->rVMCallerId;
        $json['To']                  = $this->to;
        $json['VoiceMailURL']        = $this->voiceMailURL;
        $json['Method']              = $this->method;
        $json['StatusCallBackUrl']   = $this->statusCallBackUrl;
        $json['StatsCallBackMethod'] = $this->statsCallBackMethod;

        return $json;
    }
}
