<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body61 implements JsonSerializable
{
    /**
     * List of valid Shortcode to your Ytel account
     * @required
     * @maps Shortcode
     * @var string $shortcode public property
     */
    public $shortcode;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $shortcode Initialization value for $this->shortcode
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->shortcode = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Shortcode'] = $this->shortcode;

        return $json;
    }
}
