<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body59 implements JsonSerializable
{
    /**
     * The unique identifier of each keyword
     * @required
     * @maps Keywordid
     * @var string $keywordid public property
     */
    public $keywordid;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $keywordid Initialization value for $this->keywordid
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->keywordid = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Keywordid'] = $this->keywordid;

        return $json;
    }
}
