<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body5 implements JsonSerializable
{
    /**
     * Number type either SMS,Voice or all
     * @required
     * @var string $numbertype public property
     */
    public $numbertype;

    /**
     * Specifies the area code for the returned list of available numbers. Only available for North
     * American numbers.
     * @required
     * @var string $areacode public property
     */
    public $areacode;

    /**
     * The count of objects to return.
     * @var integer|null $pagesize public property
     */
    public $pagesize;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $numbertype Initialization value for $this->numbertype
     * @param string  $areacode   Initialization value for $this->areacode
     * @param integer $pagesize   Initialization value for $this->pagesize
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->numbertype = func_get_arg(0);
            $this->areacode   = func_get_arg(1);
            $this->pagesize   = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['numbertype'] = $this->numbertype;
        $json['areacode']   = $this->areacode;
        $json['pagesize']   = $this->pagesize;

        return $json;
    }
}
