<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body46 implements JsonSerializable
{
    /**
     * The unique identifier for the voice call.
     * @required
     * @var string $callsid public property
     */
    public $callsid;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $callsid Initialization value for $this->callsid
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->callsid = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['callsid'] = $this->callsid;

        return $json;
    }
}
