<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body64 implements JsonSerializable
{
    /**
     * The unique identifier for a conference.
     * @required
     * @maps ConferenceSid
     * @var string $conferenceSid public property
     */
    public $conferenceSid;

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     * @maps Page
     * @var integer|null $page public property
     */
    public $page;

    /**
     * The count of objects to return per page.
     * @maps Pagesize
     * @var integer|null $pagesize public property
     */
    public $pagesize;

    /**
     * Specifies if participant should be muted.
     * @maps Muted
     * @var bool|null $muted public property
     */
    public $muted;

    /**
     * Specifies if the participant should hear audio in the conference.
     * @maps Deaf
     * @var bool|null $deaf public property
     */
    public $deaf;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $conferenceSid Initialization value for $this->conferenceSid
     * @param integer $page          Initialization value for $this->page
     * @param integer $pagesize      Initialization value for $this->pagesize
     * @param bool    $muted         Initialization value for $this->muted
     * @param bool    $deaf          Initialization value for $this->deaf
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->conferenceSid = func_get_arg(0);
            $this->page          = func_get_arg(1);
            $this->pagesize      = func_get_arg(2);
            $this->muted         = func_get_arg(3);
            $this->deaf          = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['ConferenceSid'] = $this->conferenceSid;
        $json['Page']          = $this->page;
        $json['Pagesize']      = $this->pagesize;
        $json['Muted']         = $this->muted;
        $json['Deaf']          = $this->deaf;

        return $json;
    }
}
