<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Body53 implements JsonSerializable
{
    /**
     * The type (category) of template Valid values: marketing, authorization
     * @var string|null $type public property
     */
    public $type;

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     * @var integer|null $page public property
     */
    public $page;

    /**
     * The count of objects to return per page.
     * @var integer|null $pagesize public property
     */
    public $pagesize;

    /**
     * Only list templates of type
     * @maps Shortcode
     * @var string|null $shortcode public property
     */
    public $shortcode;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $type      Initialization value for $this->type
     * @param integer $page      Initialization value for $this->page
     * @param integer $pagesize  Initialization value for $this->pagesize
     * @param string  $shortcode Initialization value for $this->shortcode
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->type      = func_get_arg(0);
            $this->page      = func_get_arg(1);
            $this->pagesize  = func_get_arg(2);
            $this->shortcode = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['type']      = $this->type;
        $json['page']      = $this->page;
        $json['pagesize']  = $this->pagesize;
        $json['Shortcode'] = $this->shortcode;

        return $json;
    }
}
