<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * How Ytel should handle the receiving numbers voicemail machine
 */
class IfMachineEnum
{
    /**
     * TODO: Write general description for this element
     */
    const CONTINUE_ = "continue";

    /**
     * TODO: Write general description for this element
     */
    const HANGUP = "hangup";
}
