<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * The capability supported by the number.Number type either SMS,Voice or all
 */
class NumberTypeEnum
{
    /**
     * TODO: Write general description for this element
     */
    const ALL = "all";

    /**
     * TODO: Write general description for this element
     */
    const VOICE = "voice";

    /**
     * TODO: Write general description for this element
     */
    const SMS = "sms";
}
