<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * The leg of the call DTMF digits should be sent to
 */
class PlayDtmfDirectionEnum
{
    /**
     * TODO: Write general description for this element
     */
    const IN = "in";

    /**
     * TODO: Write general description for this element
     */
    const OUT = "out";

    /**
     * TODO: Write general description for this element
     */
    const BOTH = "both";
}
