<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * Status to set the in-progress call to
 */
class Status1Enum
{
    /**
     * TODO: Write general description for this element
     */
    const CANCELED = "canceled";

    /**
     * TODO: Write general description for this element
     */
    const COMPLETED = "completed";
}
