<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib;

use YtelAPILib\Controllers;

/**
 * YtelAPILib client class
 */
class YtelAPIClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $basicAuthUserName = null,
        $basicAuthPassword = null
    ) {
        Configuration::$basicAuthUserName = $basicAuthUserName ? $basicAuthUserName : Configuration::$basicAuthUserName;
        Configuration::$basicAuthPassword = $basicAuthPassword ? $basicAuthPassword : Configuration::$basicAuthPassword;
    }
    /**
     * Singleton access to Usage controller
     * @return Controllers\UsageController The *Singleton* instance
     */
    public function getUsage()
    {
        return Controllers\UsageController::getInstance();
    }
    /**
     * Singleton access to SubAccount controller
     * @return Controllers\SubAccountController The *Singleton* instance
     */
    public function getSubAccount()
    {
        return Controllers\SubAccountController::getInstance();
    }
    /**
     * Singleton access to Account controller
     * @return Controllers\AccountController The *Singleton* instance
     */
    public function getAccount()
    {
        return Controllers\AccountController::getInstance();
    }
    /**
     * Singleton access to Email controller
     * @return Controllers\EmailController The *Singleton* instance
     */
    public function getEmail()
    {
        return Controllers\EmailController::getInstance();
    }
    /**
     * Singleton access to Recording controller
     * @return Controllers\RecordingController The *Singleton* instance
     */
    public function getRecording()
    {
        return Controllers\RecordingController::getInstance();
    }
    /**
     * Singleton access to Transcription controller
     * @return Controllers\TranscriptionController The *Singleton* instance
     */
    public function getTranscription()
    {
        return Controllers\TranscriptionController::getInstance();
    }
    /**
     * Singleton access to Conference controller
     * @return Controllers\ConferenceController The *Singleton* instance
     */
    public function getConference()
    {
        return Controllers\ConferenceController::getInstance();
    }
    /**
     * Singleton access to PhoneNumber controller
     * @return Controllers\PhoneNumberController The *Singleton* instance
     */
    public function getPhoneNumber()
    {
        return Controllers\PhoneNumberController::getInstance();
    }
    /**
     * Singleton access to Carrier controller
     * @return Controllers\CarrierController The *Singleton* instance
     */
    public function getCarrier()
    {
        return Controllers\CarrierController::getInstance();
    }
    /**
     * Singleton access to DedicatedShortCode controller
     * @return Controllers\DedicatedShortCodeController The *Singleton* instance
     */
    public function getDedicatedShortCode()
    {
        return Controllers\DedicatedShortCodeController::getInstance();
    }
    /**
     * Singleton access to SharedShortCode controller
     * @return Controllers\SharedShortCodeController The *Singleton* instance
     */
    public function getSharedShortCode()
    {
        return Controllers\SharedShortCodeController::getInstance();
    }
    /**
     * Singleton access to SMS controller
     * @return Controllers\SMSController The *Singleton* instance
     */
    public function getSMS()
    {
        return Controllers\SMSController::getInstance();
    }
    /**
     * Singleton access to Voice controller
     * @return Controllers\VoiceController The *Singleton* instance
     */
    public function getVoice()
    {
        return Controllers\VoiceController::getInstance();
    }
}
